##
## EPITECH PROJECT, 2021
## qui lit ca meme ?
## File description:
## Makefile ...
##

all:
		make -C ./lists
		make -C ./sockets
		make -C ./messages

clean:
		make -C ./lists clean
		make -C ./sockets clean
		make -C ./messages clean

fclean:
		make -C ./lists fclean
		make -C ./sockets fclean
		make -C ./messages fclean
tests_run:
		make -C ./lists tests_run
		make -C ./sockets tests_run
		make -C ./messages tests_run
re:
		make -C ./lists re
		make -C ./sockets re
		make -C ./messages re