##
## EPITECH PROJECT, 2021
## qui lit ca meme ?
## File description:
## Makefile ...
##

all:
		make -C ./lists
		make -C ./sockets

clean:
		make -C ./lists clean
		make -C ./sockets clean

fclean:
		make -C ./lists fclean
		make -C ./sockets fclean
tests_run:
		make -C ./lists test_run
		make -C ./sockets test_run
re:
		make -C ./lists re
		make -C ./sockets re