name: Tests Run CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install criterion
      run:  |
        sudo add-apt-repository ppa:snaipewastaken/ppa
        sudo apt-get update
        sudo apt-get install criterion-dev

    - name: Run tests
      run: make tests_run
